\\n should be changed to \n only when escapeSpecialCharacters is set
dmnd/dedent pull request #91
Opened 2024-03-31 20:15 UTC by fuenfundachtzig

This PR proposes a fix to the issue #90.

## PR Checklist

- [x] Addresses an existing open issue: fixes #90
- [ ] That issue was marked as [`status: accepting prs`](https://github.com/dmnd/dedent/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/dmnd/dedent/blob/main/.github/CONTRIBUTING.md) were taken

2024-04-09 20:19 UTC, JoshuaKGoldberg commented on package.json
> +	"version": "1.5.2",
No need 🙂 I'll manage this. If other PRs come in the version might not be 1.5.*.

```suggestion
	"version": "1.5.1",
```

2024-04-09 20:20 UTC, JoshuaKGoldberg requested changes
LGTM! Could you add a test to `dedent-tests.ts` please?

2024-04-10 16:53 UTC, fuenfundachtzig commented
> LGTM! Could you add a test to `dedent-tests.ts` please?

Thanks! I have added a test.

2024-04-10 17:56 UTC, JoshuaKGoldberg approved these changes
🔥 thanks!

2024-04-10 19:07 UTC, merged